scalar Object

type Query{
    ping: String
    getAllUsers: Object
    getAllAdmin: Object
    getAllCategory:Object
}

type Mutation {
    createUser(user: User!): Object
    updateUser(userId: String! , user:User):Object
    deleteUser(userId:String!):Object

    createAdmin(adminDTO: AdminDTO!): Object
    updateAdmin(adminId:String! , adminDTO:AdminDTO):Object
    deleteAdmin(adminId:String!):Object

    addProduct(products: Products!): Object
    updateProduct(productId: String ,product:Products):Object
    createCategory(category: Category!):Object

    createSupplier(supplier:Supplier!):Object
    updateSupplier(supplierId:String!,supplier:Supplier):Object



}










input User{
    userName: String!
    password: String!
    email:String!
    phoneNumber:String!
}
input AdminDTO {

    adminName: String!
    dateOfBirth: String!  # Date in String format
}

input Products{
    productName: String!
    productPrice:Float !
    costPrice:Float!
    itemCategory:String!
    description :String!

}

input Category{
    categoryName: String!
}

input Supplier{
    supplierName:String!
    supplierContact:String!
    companyName:String!
    supplierEmail:String!
}