# Application name
spring.application.name=PoS

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/posdb

# Spring GraphQL configuration
spring.graphql.graphiql.enabled=true
spring.graphql.playground.enabled=true
spring.graphql.playground.path=/playground
spring.graphql.websocket.path=/graphql
spring.graphql.path=/graphql


# File upload configuration for GraphQL
graphql.servlet.upload.maxFileSize=10MB
graphql.servlet.upload.maxRequestSize=20MB
